tasks:

- source: tasks\load.py
  product:
    df: output\load-df.parquet
    nb: output\load.ipynb
  params:
    sample: '{{sample}}'
  on_finish: data_quality.no_nas

- source: tasks\clean.py
  product:
    df: output\clean-df.parquet
    nb: output\clean.ipynb

- source: tasks\train-test-split.py
  product:
    y_train: output\train-test-split-y_train.pkl
    y_test: output\train-test-split-y_test.pkl
    X_train: output\train-test-split-X_train.pkl
    X_test: output\train-test-split-X_test.pkl
    nb: output\train-test-split.ipynb

- source: tasks\linear-regression.py
  product:
    nb: output\linear-regression.ipynb

- source: tasks\random-forest-regressor.py
  product:
    nb: output\random-forest-regressor.ipynb

- source: tasks\fit.ipynb
  product:
    nb: output\fit.html
    
    